language: generic
git:
  depth: 1
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test > /dev/null 2>&1
  - sudo add-apt-repository -y ppa:h-rayflood/llvm > /dev/null 2>&1
  - sudo apt-get update -qq
  - sudo apt-get -qq -y build-dep emacs > /dev/null 2>&1
  - wget -q http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.gz
  - tar xf emacs-24.5.tar.gz
  - cd emacs-24.5
  - ./configure > /dev/null 2>&1
  - make > /dev/null 2>&1
  - sudo make install > /dev/null 2>&1
  - cd ../
  - sudo apt-get install --allow-unauthenticated -y -qq g++-5 clang-3.4 leiningen
  - ./build > /dev/null
script:
  - cd src/
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
  - lein test
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/clang++-3.4 60
  - lein test
  - cd ../
  - mkdir release
  - mv ferret release/
  - mv src/ferret.jar release/
  - mv ferret-manual.html release/
  - mv org-mode-assets release/ferret-styles
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: dropbox.nakkaya.com
  skip_cleanup: true
  upload-dir: builds
  local-dir: release
  acl: public_read
  detect_encoding: true
notifications:
  email:
    on_success: never
    on_failure: always