sudo: required
services:
  - docker
language: generic
branches:
  only:
    - master
install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
script:
  - make docker-release
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: ferret-lang.org
  skip_cleanup: true
  local-dir: release
  acl: public_read
  detect_encoding: true
after_deploy:
  - make clojars
notifications:
  email:
    on_success: never
    on_failure: always
